main:
  partitions:
  
  - name: first_wiener_process
    iteration: firstWienerProcess
    params:
      variances: [1.0, 1.0, 1.0, 1.0, 1.0]
    init_state_values: [0.45, 1.4, 0.01, -0.13, 0.7]
    state_history_depth: 1
    seed: 7167
    extra_packages:
    - github.com/umbralcalc/stochadex/pkg/continuous
    extra_vars:
    - firstWienerProcess: "&continuous.WienerProcessIteration{}"

  - name: second_wiener_process
    iteration: secondWienerProcess
    params:
      variances: [1.0, 1.0, 1.0]
    init_state_values: [0.0, 0.0, 0.0]
    state_history_depth: 1
    seed: 2939
    extra_packages:
    - github.com/umbralcalc/stochadex/pkg/continuous
    extra_vars:
    - secondWienerProcess: "&continuous.WienerProcessIteration{}"

  simulation:

    output_condition: "&simulator.EveryStepOutputCondition{}"
    output_function: 'simulator.NewJsonLogOutputFunction("./log/test.log")'
    termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 100}"
    timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
    init_time_value: 0.0