simulator:
  iterations:
  - "&phenomena.WienerProcessIteration{}"
  - "&phenomena.WienerProcessIteration{}"
  output_condition: "&simulator.EveryStepOutputCondition{}"
  output_function: "&simulator.StdoutOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 100}"
  timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
agents:
- actor: "&interactions.DoNothingActor{}"
  generator: "&interactions.DoNothingActionGenerator{}"
  observation: "&interactions.GaussianNoiseStateObservation{}"
- actor: "&interactions.DoNothingActor{}"
  generator: "&interactions.DoNothingActionGenerator{}"
  observation: "&interactions.GaussianNoiseStateObservation{}"