simulator:
  partitions:
  - iteration: firstWienerProcess
    params_from_upstream_partition: {}
  - iteration: secondWienerProcess
    params_from_upstream_partition: {}
  output_condition: "&simulator.EveryStepOutputCondition{}"
  output_function: "&simulator.StdoutOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 100}"
  timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
extra_vars_by_package:
- github.com/umbralcalc/stochadex/pkg/phenomena:
  - firstWienerProcess: "&phenomena.WienerProcessIteration{}"
  - secondWienerProcess: "&phenomena.WienerProcessIteration{}"