simulator:
  iterations:
  - "&phenomena.WienerProcessIteration{}"
  - "&phenomena.WienerProcessIteration{}"
  output_condition: "&simulator.EveryStepOutputCondition{}"
  output_function: "&simulator.StdoutOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 1000}"
  timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
agents:
- actors:
    parametric: "&interactions.DoNothingParametricActor{}"
    state: "&interactions.DoNothingStateActor{}"
  generator: "&interactions.DoNothingActionGenerator{}"
  observation: "&interactions.GaussianNoiseStateObservation{}"
- actors:
    parametric: "&interactions.DoNothingParametricActor{}"
    state: "&interactions.DoNothingStateActor{}"
  generator: "&interactions.DoNothingActionGenerator{}"
  observation: "&interactions.GaussianNoiseStateObservation{}"