other_params:
- float_params:
    variances: [1.0, 1.0, 1.0, 1.0, 1.0]
  int_params: {}
- float_params:
    observation_noise_variances: [0.5, 0.5, 0.5, 0.5, 0.5]
  int_params:
    partition_to_observe: [0]
- float_params: {}
  int_params: {}
- float_params:
    variances: [1.0, 1.0, 1.0]
  int_params: {}
- float_params:
    observation_noise_variances: [0.5, 0.5, 0.5]
  int_params:
    partition_to_observe: [3]
- float_params: {}
  int_params: {}
init_state_values:
- [0.45, 1.4, 0.01, -0.13, 0.7]
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [1.0, 1.0, 0.0, 0.0, 1.0]
- [0.67, -0.01, 0.1]
- [0.0, 0.0, 0.0]
- [1.0, 1.0, 0.0]
init_time_value: 0.0
seeds: [4673, 111, 232, 7167, 1024, 2939]
state_widths: [5, 5, 5, 3, 3, 3]
state_history_depths: [2, 2, 2, 2, 2, 2]
timesteps_history_depth: 2