# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashboard.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dashboard.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\017./pkg/simulator',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x61shboard.proto\"_\n\x17\x44\x61shboardPartitionState\x12\x1c\n\x14\x63umulative_timesteps\x18\x01 \x01(\x01\x12\x17\n\x0fpartition_index\x18\x02 \x01(\x03\x12\r\n\x05state\x18\x03 \x03(\x01\x42\x11Z\x0f./pkg/simulatorb\x06proto3'
)




_DASHBOARDPARTITIONSTATE = _descriptor.Descriptor(
  name='DashboardPartitionState',
  full_name='DashboardPartitionState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cumulative_timesteps', full_name='DashboardPartitionState.cumulative_timesteps', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partition_index', full_name='DashboardPartitionState.partition_index', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='DashboardPartitionState.state', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['DashboardPartitionState'] = _DASHBOARDPARTITIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DashboardPartitionState = _reflection.GeneratedProtocolMessageType('DashboardPartitionState', (_message.Message,), {
  'DESCRIPTOR' : _DASHBOARDPARTITIONSTATE,
  '__module__' : 'dashboard_pb2'
  # @@protoc_insertion_point(class_scope:DashboardPartitionState)
  })
_sym_db.RegisterMessage(DashboardPartitionState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
