simulator:
  iterations:
  - - dataStream
    - rollingMean
    - rollingCovMat
  - - lastObjectiveValues
    - paramsPosteriorMeanProcess - create a new posterior iterator which Bayesian updates the mean 
    - paramsPosteriorCovmatProcess - and covariance based on the most recent sample and the last mean/cov and a cumulative objective weighting
    - paramsGeneratingProcess - extend the data generation to optionally take in dist params from serially-upstream partitions
    - processReadingParams
  output_condition: "&simulator.EveryStepOutputCondition{}"
  output_function: "&simulator.StdoutOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 100}"
  timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
extra_vars_by_package:
- github.com/umbralcalc/stochadex/pkg/phenomena:
  - firstWienerProcess: "&phenomena.WienerProcessIteration{}"
  - secondWienerProcess: "&phenomena.WienerProcessIteration{}"
  - actions: "&phenomena.WienerProcessIteration{}"
- github.com/umbralcalc/stochadex/pkg/actors:
  - someAdditiveActor: "&actors.ActorIteration{Actor: &actors.AdditiveActor{}, ActionsInput: actions}"