simulator:
  partitions:
  - iteration: dataStream
    params_by_upstream_partition: {}
  - iteration: dataRollingMean
    params_by_upstream_partition:
      0 : "latest_data_values"
  - iteration: dataRollingCov
    params_by_upstream_partition:
      0 : "latest_data_values"
      1 : "mean"
  - iteration: paramsPosteriorMean
    params_by_upstream_partition: {}
  - iteration: paramsPosteriorCov
    params_by_upstream_partition:
      3 : "mean"
  - iteration: paramsGeneratingProcess
    params_by_upstream_partition:
      3 : "mean"
      4 : "covariance_matrix"
  - iteration: simulationReadingParams
    params_by_upstream_partition:
      5 : "param_values"
  - iteration: dataComparisonToSimulation
    params_by_upstream_partition:
      1 : "mean"
      2 : "covariance_matrix"
      6 : "latest_data_values"
  output_condition: "&simulator.EveryStepOutputCondition{}"
  output_function: "&simulator.StdoutOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 1000}"
  timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
extra_vars_by_package:
- github.com/umbralcalc/stochadex/pkg/kernels:
  - expKernel: "&kernels.ExponentialIntegrationKernel{}"
- github.com/umbralcalc/stochadex/pkg/phenomena:
  - simulationIteration: "&phenomena.OrnsteinUhlenbeckIteration{}"
  - dataRollingMean: "&phenomena.WeightedWindowedMeanIteration{Kernel: expKernel}"
  - dataRollingCov: "&phenomena.WeightedWindowedCovarianceIteration{Kernel: expKernel}"
- github.com/umbralcalc/stochadex/pkg/params:
  - simulationReadingParams: "&params.ParamsReaderIteration{Iteration: simulationIteration}"
- github.com/umbralcalc/stochadex/pkg/inference:
  - likelihoodForGen: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp: "&inference.NormalLikelihoodDistribution{}"
  - dataStream: "&inference.DataGenerationIteration{Likelihood: likelihoodForGen}"
  - dataComparisonToSimulation: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp}"
  - paramsPosteriorMean: "&inference.PosteriorMeanIteration{}"
  - paramsPosteriorCov: "&inference.PosteriorCovarianceIteration{}"
  - likelihoodForParamsGen: "&inference.NormalLikelihoodDistribution{}"
  - paramsGeneratingProcess: "&inference.DataGenerationIteration{Likelihood: likelihoodForParamsGen}"