other_params:
- float_params:
    mean: []
    covariance_matrix: []
  int_params: {}
- float_params:
    exponential_weighting_timescale: []
  int_params: {}
- float_params:
    exponential_weighting_timescale: []
  int_params: {}
- float_params:
    past_discounting_factor: []
  int_params:
    param_partitions: []
    loglike_partitions: []
- float_params:
    past_discounting_factor: []
  int_params:
    param_partitions: []
    loglike_partitions: []
- float_params: {}
  int_params: {}
- float_params:
    mus: []
    sigmas: []
    thetas: []
  int_params: {}
- float_params: {}
  int_params: {}
init_state_values:
- [0.45, 1.4, 0.01, -0.13, 0.7]
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.67, -0.01, 0.1]
init_time_value: 0.0
seeds: [7167, 1024, 2939]
state_widths: [5, 5, 3]
state_history_depths: [2, 2, 2]
timesteps_history_depth: 2