# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cmd/messages/action_state.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'cmd/messages/action_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63md/messages/action_state.proto\"\x91\x01\n\x0b\x41\x63tionState\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12\x30\n\npartitions\x18\x02 \x03(\x0b\x32\x1c.ActionState.PartitionsEntry\x1a@\n\x0fPartitionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.ActionValues:\x02\x38\x01\"\x1e\n\x0c\x41\x63tionValues\x12\x0e\n\x06values\x18\x01 \x03(\x01\x42\x11Z\x0f./pkg/simulatorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cmd.messages.action_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./pkg/simulator'
  _globals['_ACTIONSTATE_PARTITIONSENTRY']._loaded_options = None
  _globals['_ACTIONSTATE_PARTITIONSENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONSTATE']._serialized_start=36
  _globals['_ACTIONSTATE']._serialized_end=181
  _globals['_ACTIONSTATE_PARTITIONSENTRY']._serialized_start=117
  _globals['_ACTIONSTATE_PARTITIONSENTRY']._serialized_end=181
  _globals['_ACTIONVALUES']._serialized_start=183
  _globals['_ACTIONVALUES']._serialized_end=213
# @@protoc_insertion_point(module_scope)
