# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cmd/messages/partition_state.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'cmd/messages/partition_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"cmd/messages/partition_state.proto\"U\n\x0ePartitionState\x12\x1c\n\x14\x63umulative_timesteps\x18\x01 \x01(\x01\x12\x16\n\x0epartition_name\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x03(\x01\x42\x11Z\x0f./pkg/simulatorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cmd.messages.partition_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./pkg/simulator'
  _globals['_PARTITIONSTATE']._serialized_start=38
  _globals['_PARTITIONSTATE']._serialized_end=123
# @@protoc_insertion_point(module_scope)
