// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cmd/messages/partition_state.proto

package simulator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartitionState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CumulativeTimesteps float64                `protobuf:"fixed64,1,opt,name=cumulative_timesteps,json=cumulativeTimesteps,proto3" json:"cumulative_timesteps,omitempty"`
	PartitionName       string                 `protobuf:"bytes,2,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	State               []float64              `protobuf:"fixed64,3,rep,packed,name=state,proto3" json:"state,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PartitionState) Reset() {
	*x = PartitionState{}
	mi := &file_cmd_messages_partition_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionState) ProtoMessage() {}

func (x *PartitionState) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_messages_partition_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionState.ProtoReflect.Descriptor instead.
func (*PartitionState) Descriptor() ([]byte, []int) {
	return file_cmd_messages_partition_state_proto_rawDescGZIP(), []int{0}
}

func (x *PartitionState) GetCumulativeTimesteps() float64 {
	if x != nil {
		return x.CumulativeTimesteps
	}
	return 0
}

func (x *PartitionState) GetPartitionName() string {
	if x != nil {
		return x.PartitionName
	}
	return ""
}

func (x *PartitionState) GetState() []float64 {
	if x != nil {
		return x.State
	}
	return nil
}

var File_cmd_messages_partition_state_proto protoreflect.FileDescriptor

const file_cmd_messages_partition_state_proto_rawDesc = "" +
	"\n" +
	"\"cmd/messages/partition_state.proto\"\x80\x01\n" +
	"\x0ePartitionState\x121\n" +
	"\x14cumulative_timesteps\x18\x01 \x01(\x01R\x13cumulativeTimesteps\x12%\n" +
	"\x0epartition_name\x18\x02 \x01(\tR\rpartitionName\x12\x14\n" +
	"\x05state\x18\x03 \x03(\x01R\x05stateB\x11Z\x0f./pkg/simulatorb\x06proto3"

var (
	file_cmd_messages_partition_state_proto_rawDescOnce sync.Once
	file_cmd_messages_partition_state_proto_rawDescData []byte
)

func file_cmd_messages_partition_state_proto_rawDescGZIP() []byte {
	file_cmd_messages_partition_state_proto_rawDescOnce.Do(func() {
		file_cmd_messages_partition_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_messages_partition_state_proto_rawDesc), len(file_cmd_messages_partition_state_proto_rawDesc)))
	})
	return file_cmd_messages_partition_state_proto_rawDescData
}

var file_cmd_messages_partition_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_messages_partition_state_proto_goTypes = []any{
	(*PartitionState)(nil), // 0: PartitionState
}
var file_cmd_messages_partition_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_messages_partition_state_proto_init() }
func file_cmd_messages_partition_state_proto_init() {
	if File_cmd_messages_partition_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_messages_partition_state_proto_rawDesc), len(file_cmd_messages_partition_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_messages_partition_state_proto_goTypes,
		DependencyIndexes: file_cmd_messages_partition_state_proto_depIdxs,
		MessageInfos:      file_cmd_messages_partition_state_proto_msgTypes,
	}.Build()
	File_cmd_messages_partition_state_proto = out.File
	file_cmd_messages_partition_state_proto_goTypes = nil
	file_cmd_messages_partition_state_proto_depIdxs = nil
}
