iterations:
- "dummyProcessIteration"
- "dummyProcessIteration"
output_condition: "EveryStepOutputCondition"
output_function: "NilOutputFunction"
termination_condition: "NumberOfStepsTerminationCondition"
termination_condition_config:
  max_number_of_steps: 1000
timestep_function: "ConstantTimestepFunction"
timestep_function_config:
  stepsize: 1.0