// Command model-index generates the domain model index: a generated view across
// every catalogue model of which core packages it builds on, which bespoke
// iterations sit beside its stub, and whether its behaviour claims are test-bound.
// It makes the generality thesis checkable — one engine, heterogeneous domains —
// rather than asserted, and surfaces the promotion signal (a bespoke concept
// recurring across models wants promoting into core).
//
// Everything is derived by inspecting the real stubs (imports and the types that
// implement simulator.Iteration), never hand-maintained. Re-run after adding or
// changing a model:
//
//	go run ./cmd/model-index
//
// It writes two artifacts: models/INDEX.md (the human page) and models/index.json
// (the machine-readable agent-discovery surface). TestModelIndexUpToDate guards
// that the committed artifacts match, so CI fails if the index drifts from the code.
package main

//go:generate go run .

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// Model is one catalogue entry's inspected structure.
type Model struct {
	Dir          string   `json:"dir"`
	CorePackages []string `json:"core_packages"`      // e.g. ["pkg/continuous", "pkg/simulator"]
	Bespoke      []string `json:"bespoke_iterations"` // types implementing simulator.Iteration
	Bound        bool     `json:"behaviour_bound"`    // exposes ObservedBehaviour() (test-bound card)
}

// Index is the whole generated artifact.
type Index struct {
	Note             string              `json:"note"`
	Models           []Model             `json:"models"`
	CorePackageUsage map[string][]string `json:"core_package_usage"` // package -> models using it
	SharedConcepts   []SharedConcept     `json:"shared_concept_hints"`
}

// SharedConcept is a best-effort promotion hint: a name token appearing in the
// bespoke iterations of more than one model. It is a signal for a maintainer to
// judge, not an automatic promotion decision.
type SharedConcept struct {
	Token  string   `json:"token"`
	Models []string `json:"models"`
}

const note = "GENERATED by cmd/model-index — do not edit by hand. " +
	"Everything here is derived by inspecting the model stubs (imports and the " +
	"types implementing simulator.Iteration). Regenerate with `go run ./cmd/model-index`."

// inspectModel parses a model directory's non-test Go files and extracts its core
// package imports, the iterations it defines, and whether it is behaviour-bound.
func inspectModel(dir string) (Model, error) {
	m := Model{Dir: filepath.Base(dir)}
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return m, err
	}

	coreSet := map[string]struct{}{}
	bespokeSet := map[string]struct{}{}
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, imp := range file.Imports {
				path := strings.Trim(imp.Path.Value, `"`)
				if i := strings.Index(path, "umbralcalc/stochadex/pkg/"); i >= 0 {
					coreSet["pkg/"+strings.TrimPrefix(path[i:], "umbralcalc/stochadex/pkg/")] = struct{}{}
				}
			}
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok {
					continue
				}
				// A type implementing simulator.Iteration has an Iterate method.
				if fn.Recv != nil && fn.Name.Name == "Iterate" {
					bespokeSet[receiverType(fn.Recv)] = struct{}{}
				}
				// A behaviour-bound model exposes a package-level ObservedBehaviour().
				if fn.Recv == nil && fn.Name.Name == "ObservedBehaviour" {
					m.Bound = true
				}
			}
		}
	}
	m.CorePackages = sortedKeys(coreSet)
	m.Bespoke = sortedKeys(bespokeSet)
	return m, nil
}

// receiverType returns the (pointer-stripped) receiver type name of a method.
func receiverType(recv *ast.FieldList) string {
	if len(recv.List) == 0 {
		return ""
	}
	switch t := recv.List[0].Type.(type) {
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}

func sortedKeys(m map[string]struct{}) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		if k != "" {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}

// splitCamel splits a CamelCase identifier into lower-cased word tokens, dropping a
// trailing "Iteration".
func splitCamel(s string) []string {
	s = strings.TrimSuffix(s, "Iteration")
	var tokens []string
	var cur strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			tokens = append(tokens, strings.ToLower(cur.String()))
			cur.Reset()
		}
		cur.WriteRune(r)
	}
	if cur.Len() > 0 {
		tokens = append(tokens, strings.ToLower(cur.String()))
	}
	return tokens
}

// build assembles the index from the inspected models.
func build(models []Model) Index {
	usage := map[string]map[string]struct{}{}
	for _, m := range models {
		for _, p := range m.CorePackages {
			if usage[p] == nil {
				usage[p] = map[string]struct{}{}
			}
			usage[p][m.Dir] = struct{}{}
		}
	}
	corePackageUsage := map[string][]string{}
	for p, set := range usage {
		corePackageUsage[p] = sortedKeys(set)
	}

	// Shared-concept hints: a name token appearing in the bespoke iterations of
	// more than one model. Best-effort promotion signal for the maintainer.
	tokenModels := map[string]map[string]struct{}{}
	for _, m := range models {
		for _, name := range m.Bespoke {
			for _, tok := range splitCamel(name) {
				if tokenModels[tok] == nil {
					tokenModels[tok] = map[string]struct{}{}
				}
				tokenModels[tok][m.Dir] = struct{}{}
			}
		}
	}
	var shared []SharedConcept
	for tok, set := range tokenModels {
		if len(set) >= 2 {
			shared = append(shared, SharedConcept{Token: tok, Models: sortedKeys(set)})
		}
	}
	sort.Slice(shared, func(i, j int) bool { return shared[i].Token < shared[j].Token })

	return Index{Note: note, Models: models, CorePackageUsage: corePackageUsage, SharedConcepts: shared}
}

func renderMarkdown(idx Index) string {
	var b strings.Builder
	b.WriteString("# Domain model index\n\n")
	b.WriteString("<!-- " + note + " -->\n\n")
	b.WriteString("_This page is generated by `cmd/model-index` from the model stubs — it is the " +
		"checkable form of the generality claim (one engine, many domains) and the surface on " +
		"which the extension-promotion signal becomes visible. `TestModelIndexUpToDate` fails CI " +
		"if it drifts from the code._\n\n")

	b.WriteString("## Models\n\n")
	b.WriteString("| Model | Core packages | Bespoke iterations | Behaviour-bound |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, m := range idx.Models {
		bound := "—"
		if m.Bound {
			bound = "✓"
		}
		bespoke := "—"
		if len(m.Bespoke) > 0 {
			bespoke = fmt.Sprintf("%d: `%s`", len(m.Bespoke), strings.Join(m.Bespoke, "`, `"))
		}
		core := "—"
		if len(m.CorePackages) > 0 {
			core = "`" + strings.Join(m.CorePackages, "`, `") + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", m.Dir, core, bespoke, bound)
	}

	b.WriteString("\n## Core-package reuse\n\n")
	b.WriteString("How many models build on each engine package — the concrete reuse behind the " +
		"generality claim.\n\n")
	b.WriteString("| Core package | Models |\n|---|---|\n")
	pkgs := make([]string, 0, len(idx.CorePackageUsage))
	for p := range idx.CorePackageUsage {
		pkgs = append(pkgs, p)
	}
	sort.Slice(pkgs, func(i, j int) bool {
		if len(idx.CorePackageUsage[pkgs[i]]) != len(idx.CorePackageUsage[pkgs[j]]) {
			return len(idx.CorePackageUsage[pkgs[i]]) > len(idx.CorePackageUsage[pkgs[j]])
		}
		return pkgs[i] < pkgs[j]
	})
	for _, p := range pkgs {
		ms := idx.CorePackageUsage[p]
		fmt.Fprintf(&b, "| `%s` | %d — %s |\n", p, len(ms), strings.Join(ms, ", "))
	}

	b.WriteString("\n## Promotion signal\n\n")
	if len(idx.SharedConcepts) == 0 {
		b.WriteString("No bespoke-iteration concept recurs across models yet (each model's " +
			"extensions are named distinctly). The pool of bespoke iterations above is where a " +
			"recurring concept would first appear; when one is beside three or four models it is " +
			"signalling to be promoted into core — a maintainer judgement, informed by this view. " +
			"(Conceptual recurrence not visible in type names — e.g. a mean-reverting process " +
			"reimplemented under different names — stays a maintainer judgement this heuristic " +
			"does not attempt.)\n")
	} else {
		b.WriteString("Name tokens shared by bespoke iterations across more than one model — a " +
			"best-effort hint for the maintainer to judge, not an automatic promotion:\n\n")
		b.WriteString("| Shared token | Models |\n|---|---|\n")
		for _, s := range idx.SharedConcepts {
			fmt.Fprintf(&b, "| `%s` | %s |\n", s.Token, strings.Join(s.Models, ", "))
		}
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// discoverModels returns the model directories (those containing a stub.go),
// sorted, so the index auto-tracks the catalogue with no hand-maintained list.
func discoverModels(root string) ([]string, error) {
	modelsDir := filepath.Join(root, "models")
	entries, err := os.ReadDir(modelsDir)
	if err != nil {
		return nil, err
	}
	var dirs []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(modelsDir, e.Name(), "stub.go")); err == nil {
			dirs = append(dirs, filepath.Join(modelsDir, e.Name()))
		}
	}
	sort.Strings(dirs)
	return dirs, nil
}

// generate builds the index and returns the desired file contents.
func generate(root string) (markdown string, jsonBytes []byte, err error) {
	dirs, err := discoverModels(root)
	if err != nil {
		return "", nil, err
	}
	var models []Model
	for _, d := range dirs {
		m, err := inspectModel(d)
		if err != nil {
			return "", nil, fmt.Errorf("%s: %w", filepath.Base(d), err)
		}
		models = append(models, m)
	}
	idx := build(models)
	j, err := json.MarshalIndent(idx, "", "  ")
	if err != nil {
		return "", nil, err
	}
	return renderMarkdown(idx), append(j, '\n'), nil
}

// artifactPaths returns the on-disk paths of the two generated artifacts.
func artifactPaths(root string) (mdPath, jsonPath string) {
	return filepath.Join(root, "models", "INDEX.md"), filepath.Join(root, "models", "index.json")
}

// run regenerates the index artifacts. When write is false it only reports whether
// they are stale (used by TestModelIndexUpToDate); when true it writes them.
func run(root string, write bool) (changed bool, err error) {
	md, j, err := generate(root)
	if err != nil {
		return false, err
	}
	mdPath, jsonPath := artifactPaths(root)
	for _, f := range []struct {
		path string
		want []byte
	}{{mdPath, []byte(md)}, {jsonPath, j}} {
		got, _ := os.ReadFile(f.path)
		if string(got) == string(f.want) {
			continue
		}
		changed = true
		if write {
			if err := os.WriteFile(f.path, f.want, 0o644); err != nil {
				return changed, err
			}
		}
	}
	return changed, nil
}

func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("cannot determine caller source path")
	}
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found above %s", file)
		}
		dir = parent
	}
}

func main() {
	root, err := repoRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	changed, err := run(root, true)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	if changed {
		fmt.Println("model index regenerated")
	} else {
		fmt.Println("model index already up to date")
	}
}
