other_params:
  - float_params:
    "variances":
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
  - float_params:
    "variances":
      - 1.0
      - 1.0
      - 1.0
init_state_values:
  - values:
    - 0.45
    - 1.40
    - 0.01
    - -0.13
    - 0.7
  - values:
    - 0.67
    - -0.01
    - -0.10
seeds:
  - 4673
  - 2783
state_widths:
  - 5
  - 3
state_history_depths:
  - 1
  - 1
timesteps_history_depth: 1