# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simio/simio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simio/simio.proto',
  package='main',
  syntax='proto3',
  serialized_options=_b('Z\007./simio'),
  serialized_pb=_b('\n\x11simio/simio.proto\x12\x04main\"\xf7\x02\n\x0e\x41nglersimInput\x12\x0f\n\x07runTime\x18\x01 \x01(\x01\x12\x11\n\ttimeScale\x18\x02 \x01(\x01\x12\x10\n\x08numReals\x18\x03 \x01(\x03\x12\x12\n\nnumSpecies\x18\x04 \x01(\x03\x12\x0c\n\x04seed\x18\x05 \x01(\x03\x12\x32\n\x08\x66ishPops\x18\x06 \x03(\x0b\x32 .main.AnglersimInput.FishPopType\x1a\xd8\x01\n\x0b\x46ishPopType\x12\x11\n\tinitCount\x18\x01 \x01(\x01\x12\x11\n\tbirthRate\x18\x02 \x01(\x01\x12\x14\n\x0c\x64\x65nsDepPower\x18\x03 \x01(\x01\x12\x11\n\tdeathRate\x18\x04 \x01(\x01\x12\x15\n\rpredationRate\x18\x05 \x01(\x01\x12\x1c\n\x14predatorBirthIncRate\x18\x06 \x01(\x01\x12\x13\n\x0b\x66ishingRate\x18\x07 \x01(\x01\x12\x19\n\x11predatorMatrixRow\x18\x08 \x03(\x01\x12\x15\n\rpreyMatrixRow\x18\t \x03(\x01\"2\n\x0f\x41nglersimOutput\x12\x0f\n\x07species\x18\x01 \x03(\x03\x12\x0e\n\x06\x63ounts\x18\x02 \x03(\x01\x42\tZ\x07./simiob\x06proto3')
)




_ANGLERSIMINPUT_FISHPOPTYPE = _descriptor.Descriptor(
  name='FishPopType',
  full_name='main.AnglersimInput.FishPopType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initCount', full_name='main.AnglersimInput.FishPopType.initCount', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthRate', full_name='main.AnglersimInput.FishPopType.birthRate', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='densDepPower', full_name='main.AnglersimInput.FishPopType.densDepPower', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deathRate', full_name='main.AnglersimInput.FishPopType.deathRate', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predationRate', full_name='main.AnglersimInput.FishPopType.predationRate', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predatorBirthIncRate', full_name='main.AnglersimInput.FishPopType.predatorBirthIncRate', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fishingRate', full_name='main.AnglersimInput.FishPopType.fishingRate', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predatorMatrixRow', full_name='main.AnglersimInput.FishPopType.predatorMatrixRow', index=7,
      number=8, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preyMatrixRow', full_name='main.AnglersimInput.FishPopType.preyMatrixRow', index=8,
      number=9, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=403,
)

_ANGLERSIMINPUT = _descriptor.Descriptor(
  name='AnglersimInput',
  full_name='main.AnglersimInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runTime', full_name='main.AnglersimInput.runTime', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeScale', full_name='main.AnglersimInput.timeScale', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numReals', full_name='main.AnglersimInput.numReals', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numSpecies', full_name='main.AnglersimInput.numSpecies', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seed', full_name='main.AnglersimInput.seed', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fishPops', full_name='main.AnglersimInput.fishPops', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ANGLERSIMINPUT_FISHPOPTYPE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=403,
)


_ANGLERSIMOUTPUT = _descriptor.Descriptor(
  name='AnglersimOutput',
  full_name='main.AnglersimOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='species', full_name='main.AnglersimOutput.species', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counts', full_name='main.AnglersimOutput.counts', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=455,
)

_ANGLERSIMINPUT_FISHPOPTYPE.containing_type = _ANGLERSIMINPUT
_ANGLERSIMINPUT.fields_by_name['fishPops'].message_type = _ANGLERSIMINPUT_FISHPOPTYPE
DESCRIPTOR.message_types_by_name['AnglersimInput'] = _ANGLERSIMINPUT
DESCRIPTOR.message_types_by_name['AnglersimOutput'] = _ANGLERSIMOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnglersimInput = _reflection.GeneratedProtocolMessageType('AnglersimInput', (_message.Message,), dict(

  FishPopType = _reflection.GeneratedProtocolMessageType('FishPopType', (_message.Message,), dict(
    DESCRIPTOR = _ANGLERSIMINPUT_FISHPOPTYPE,
    __module__ = 'simio.simio_pb2'
    # @@protoc_insertion_point(class_scope:main.AnglersimInput.FishPopType)
    ))
  ,
  DESCRIPTOR = _ANGLERSIMINPUT,
  __module__ = 'simio.simio_pb2'
  # @@protoc_insertion_point(class_scope:main.AnglersimInput)
  ))
_sym_db.RegisterMessage(AnglersimInput)
_sym_db.RegisterMessage(AnglersimInput.FishPopType)

AnglersimOutput = _reflection.GeneratedProtocolMessageType('AnglersimOutput', (_message.Message,), dict(
  DESCRIPTOR = _ANGLERSIMOUTPUT,
  __module__ = 'simio.simio_pb2'
  # @@protoc_insertion_point(class_scope:main.AnglersimOutput)
  ))
_sym_db.RegisterMessage(AnglersimOutput)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
