params:
- mean: [0.5, 1.0, 0.8]
  covariance_matrix: [5.0, 0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 5.0]
- exponential_weighting_timescale: [30.0]
  data_values_partition: [0]
- exponential_weighting_timescale: [30.0]
  data_values_partition: [0]
- burn_in_steps: [30]
init_state_values:
- [2.0, 1.0, 0.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0]
init_time_value: 0.0
seeds: [1162, 0, 0, 0]
state_widths: [3, 3, 9, 1]
state_history_depths: [30, 2, 2, 2]
timesteps_history_depth: 30