iterations:
- name: partition_0
  params:
    copulas_off: [1]
    mean_partition: [1]
    variance: [1.0, 3.0, 2.0]
  init_state_values: [0.0, 0.0, 0.0]
  seed: 0
  state_width: 3
  state_history_depth: 1
- name: partition_1
  params:
    ascent: [1]
    learning_rate: [0.05]
  params_from_upstream:
    gradient:
      upstream: 0
  init_state_values: [35.0, 3.6, 1.0]
  seed: 0
  state_width: 3
  state_history_depth: 1
init_time_value: 0.0
timesteps_history_depth: 1