params:
- mean: [1.5, -12.0, 4.1]
  covariance_matrix: [5.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 10.0]
- {}
- mean: [2.5, -9.0, 1.9]
  covariance_matrix: [3.0, 0.0, 0.0, 0.0, 2.8, 0.0, 0.0, 0.0, 6.6]
- {}
- past_discounting_factor: [0.98]
  loglike_partitions: [1, 3]
- param_partitions: [0, 2]
  loglike_partitions: [1, 3]
- param_partitions: [0, 2]
  loglike_partitions: [1, 3]
init_state_values:
- [1.0, -5.2, 0.2]
- [-6293.021]
- [2.8, -4.4, 1.5]
- [-7923.113]
- [0.0]
- [0.0, 0.0, 0.0]
- [3.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 3.0]
init_time_value: 0.0
seeds: [621, 0, 89912, 0, 0, 0, 0]
state_widths: [3, 1, 3, 1, 1, 3, 9]
state_history_depths: [2, 10, 2, 10, 2, 2, 2]
timesteps_history_depth: 10