iterations:
- name: partition_0
  params:
    mean: [1.5, -12.0, 4.1]
    covariance_matrix: [5.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 10.0]
  init_state_values: [1.0, -5.2, 0.2]
  seed: 5672
  state_width: 3
  state_history_depth: 1
- name: partition_1
  params:
    past_discounting_factor: [0.95]
    data_values_partition: [0]
    lower_time_delta: [0.0]
  params_from_upstream:
    latest_data_values:
      upstream: 0
  init_state_values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  seed: 0
  state_width: 10
  state_history_depth: 50
init_time_value: 0.0
timesteps_history_depth: 50