iterations:
- name: partition_0
  params:
    degrees_of_freedom: [45.0]
    scale_matrix: [7.0, 0.0, 0.0, 0.0, 2.7, 0.0, 0.0, 0.0, 1.8]
  init_state_values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  seed: 0
  state_width: 9
  state_history_depth: 1
- name: partition_1
  params:
    ascent: [1]
    learning_rate: [0.05]
  params_from_upstream:
    gradient:
      upstream: 0
  init_state_values: [7.0, 0.0, 0.0, 0.0, 2.7, 0.0, 0.0, 0.0, 1.8]
  seed: 0
  state_width: 9
  state_history_depth: 1
init_time_value: 0.0
timesteps_history_depth: 1