other_params:
- float_params:
    variances: [0.3, 1.0, 1.1, 2.0, 6.0]
  int_params: {}
- float_params: {}
  int_params: {}
- float_params:
    nan_value: [0.0]
  int_params:
    partition_to_observe: [0]
    mask_partition: [1]
init_state_values:
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 1.0, 0.0, 1.0, 1.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [36799, 0, 1228]
state_widths: [5, 5, 5]
state_history_depths: [2, 2, 2]
timesteps_history_depth: 2