other_params:
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    false_positives: [1]
    partition_to_observe: [0]
    false_observation_probs_partition: [1]
    state_value_observation_indices: [0, 1, 2, 3]
init_state_values:
- [0.0, 1.0, 1.0, 0.0]
- [0.2, 0.1, 0.4, 0.8]
- [0.0, 0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [0, 0, 1111228]
state_widths: [4, 4, 4]
state_history_depths: [2, 2, 2]
timesteps_history_depth: 2