params:
- {}
- observation_noise_variances: [0.1, 0.5, 0.9]
init_state_values:
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [0, 228]
state_widths: [3, 3]
state_history_depths: [2, 2]
timesteps_history_depth: 2