other_params:
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    state_value_observation_indices: [0, 1]
init_state_values:
- [0.0, 0.0, 0.0]
- [0.0, 0.0]
init_time_value: 0.0
seeds: [0, 0]
state_widths: [3, 2]
state_history_depths: [2, 2]
timesteps_history_depth: 2