other_params:
- float_params:
    mean: [1.8, 5.0, -7.3, 2.2]
    covariance_matrix: [2.5, 0.0, 0.0, 0.0, 0.0, 9.0, 0.0, 0.0, 0.0, 0.0, 4.4, 0.0, 0.0, 0.0, 0.0, 17.0]
  int_params: {}
- float_params:
    exponential_weighting_timescale: [100.0]
  int_params:
    data_values_partition: [0]
- float_params:
    exponential_weighting_timescale: [100.0]
  int_params:
    data_values_partition: [0]
- float_params:
    past_discounting_factor: [0.5]
  int_params:
    loglike_partitions: [8]
- float_params: {}
  int_params:
    param_partitions: [6]
    loglike_partitions: [8]
- float_params: {}
  int_params:
    param_partitions: [6]
    loglike_partitions: [8]
- float_params:
    correlation_with_previous: [0.5]
    default_covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  int_params: {}
- float_params:
    mus: [1.0, 4.0, -6.0, 1.0]
    sigmas: [1.5, 3.0, 2.2, 4.1]
    thetas: [1.0, 1.0, 1.0, 1.0]
  float_params_mask:
    mus: [true, true, true, true]
  int_params: {}
- float_params: {}
  int_params:
    burn_in_steps: [500]
init_state_values:
- [1.3, 8.3, -4.9, 1.6]
- [1.1, 4.0, -8.3, 2.0]
- [4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0]
- [0.0]
- [0.9, 3.5, -4.7, 1.0]
- [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
- [0.9, 3.5, -4.7, 1.0]
- [1.3, 8.3, -4.9, 1.6]
- [0.0]
init_time_value: 0.0
seeds: [291, 0, 0, 0, 0, 0, 11242, 6785, 0]
state_widths: [4, 4, 16, 1, 4, 16, 4, 4, 1]
state_history_depths: [500, 2, 2, 2, 2, 2, 2, 2, 200]
timesteps_history_depth: 500