iterations:
- params:
    state_value_observation_probs: [0.4, 0.8]
  init_state_values: [0.0, 0.0]
  seed: 563
  state_width: 2
  state_history_depth: 1
init_time_value: 0.0
timesteps_history_depth: 1