iterations:
- params: {}
  init_state_values: [1.0, 2.0, 1.0, 1.0, 0.3, 1.2, 0.1, 1.0, 1.0, 1.0, 2.0, 0.5]
  seed: 0
  state_width: 12
  state_history_depth: 2
- params:
    transitions_from_0: [1, 2, 3, 4]
    transitions_from_1: [3, 4, 5]
    transitions_from_2: [5]
    transitions_from_3: [1]
    transitions_from_4: [3, 2]
    transitions_from_5: [1]
  params_from_upstream:
    transition_rates:
      upstream: 0
  init_state_values: [0]
  seed: 123563
  state_width: 1
  state_history_depth: 2
init_time_value: 0.0
timesteps_history_depth: 2