iterations:
- name: partition_0
  params:
    rates: [1.5, 0.2, 0.6, 1.0, 3.0]
  init_state_values: [0.0, 0.0, 0.0, 0.0, 0.0]
  seed: 563
  state_width: 5
  state_history_depth: 2
- name: partition_1
  params: {}
  params_from_upstream:
    rates:
      upstream: 0
  init_state_values: [0.0, 0.0, 0.0, 0.0, 0.0]
  seed: 8312
  state_width: 5
  state_history_depth: 2
init_time_value: 1.0
timesteps_history_depth: 2