params:
- rates: [0.5, 1.0, 0.8, 1.0, 1.1]
- rates: [1.5, 0.2, 0.6]
init_state_values:
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [563, 8312]
state_widths: [5, 3]
state_history_depths: [2, 2]
timesteps_history_depth: 2