other_params:
- float_params: {}
  int_params: {}
- float_params:
    rates: [0.5, 1.0, 0.8, 1.0, 1.1]
  float_params_mask:
    rates: [false, true, true, false, true]
  int_params: {}
- float_params: {}
  int_params: {}
- float_params:
    rates: [1.5, 0.2, 0.6]
  float_params_mask:
    rates: [true, true, true]
  int_params: {}
init_state_values:
- [0.1, 1.7]
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [3.0, 6.2, 1.1]
- [0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [0, 563, 0, 8312]
state_widths: [2, 5, 3, 3]
state_history_depths: [2, 2, 2, 2]
timesteps_history_depth: 2