simulation:
  implementations:
    partitions:
    - iteration: dataStream
      params_from_upstream_partition: {}
    - iteration: dataRollingMean
      params_from_upstream_partition:
        "latest_data_values": 0
    - iteration: dataRollingCov
      params_from_upstream_partition:
        "latest_data_values": 0
        "mean": 1
    - iteration: paramsPosteriorLogNorm
      params_from_upstream_partition: {}
    - iteration: paramsPosteriorMean
      params_from_upstream_partition:
        "posterior_log_normalisation": 3
    - iteration: paramsPosteriorCov
      params_from_upstream_partition:
        "posterior_log_normalisation": 3
        "mean": 4
    - iteration: paramsGeneratingProcess
      params_from_upstream_partition:
        "mean": 4
        "covariance_matrix": 5
    - iteration: simulationReadingParams
      params_from_upstream_partition:
        "param_values": 6
    - iteration: dataComparisonToSimulation
      params_from_upstream_partition:
        "mean": 1
        "covariance_matrix": 2
        "latest_data_values": 7
    - iteration: paramsGeneratingProcess2
      params_from_upstream_partition:
        "mean": 4
        "covariance_matrix": 5
    - iteration: simulationReadingParams2
      params_from_upstream_partition:
        "param_values": 9
    - iteration: dataComparisonToSimulation2
      params_from_upstream_partition:
        "mean": 1
        "covariance_matrix": 2
        "latest_data_values": 10
    - iteration: paramsGeneratingProcess3
      params_from_upstream_partition:
        "mean": 4
        "covariance_matrix": 5
    - iteration: simulationReadingParams3
      params_from_upstream_partition:
        "param_values": 12
    - iteration: dataComparisonToSimulation3
      params_from_upstream_partition:
        "mean": 1
        "covariance_matrix": 2
        "latest_data_values": 13
    output_condition: "&simulator.EveryStepOutputCondition{}"
    output_function: "&simulator.StdoutOutputFunction{}"
    termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 5000}"
    timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
  settings:
    other_params:
    - float_params:
        mean: [1.8, 5.0, -7.3, 2.2]
        covariance_matrix: [2.5, 0.0, 0.0, 0.0, 0.0, 9.0, 0.0, 0.0, 0.0, 0.0, 4.4, 0.0, 0.0, 0.0, 0.0, 17.0]
      int_params: {}
    - float_params:
        exponential_weighting_timescale: [100.0]
      int_params:
        data_values_partition: [0]
    - float_params:
        exponential_weighting_timescale: [100.0]
      int_params:
        data_values_partition: [0]
    - float_params:
        past_discounting_factor: [0.5]
      int_params:
        loglike_partitions: [8, 11, 14]
    - float_params: {}
      int_params:
        param_partitions: [6, 9, 12]
        loglike_partitions: [8, 11, 14]
    - float_params: {}
      int_params:
        param_partitions: [6, 9, 12]
        loglike_partitions: [8, 11, 14]
    - float_params:
        correlation_with_previous: [0.5]
        default_covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
      int_params: {}
    - float_params:
        mus: [1.0, 4.0, -6.0, 1.0]
        sigmas: [1.5, 3.0, 2.2, 4.1]
        thetas: [1.0, 1.0, 1.0, 1.0]
      float_params_mask:
        mus: [true, true, true, true]
      int_params: {}
    - float_params: {}
      int_params:
        burn_in_steps: [500]
    - float_params:
        correlation_with_previous: [0.5]
        default_covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
      int_params: {}
    - float_params:
        mus: [1.0, 4.0, -6.0, 1.0]
        sigmas: [1.5, 3.0, 2.2, 4.1]
        thetas: [1.0, 1.0, 1.0, 1.0]
      float_params_mask:
        mus: [true, true, true, true]
      int_params: {}
    - float_params: {}
      int_params:
        burn_in_steps: [500]
    - float_params:
        correlation_with_previous: [0.5]
        default_covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
      int_params:
    - float_params:
        mus: [1.0, 4.0, -6.0, 1.0]
        sigmas: [1.5, 3.0, 2.2, 4.1]
        thetas: [1.0, 1.0, 1.0, 1.0]
      float_params_mask:
        mus: [true, true, true, true]
      int_params: {}
    - float_params: {}
      int_params:
        burn_in_steps: [500]
    init_state_values:
    - [1.3, 8.3, -4.9, 1.6]
    - [1.1, 4.0, -8.3, 2.0]
    - [4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0]
    - [0.0]
    - [0.9, 3.5, -4.7, 1.0]
    - [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    - [0.9, 3.5, -4.7, 1.0]
    - [1.3, 8.3, -4.9, 1.6]
    - [0.0]
    - [0.9, 3.5, -4.7, 1.0]
    - [1.3, 8.3, -4.9, 1.6]
    - [0.0]
    - [0.9, 3.5, -4.7, 1.0]
    - [1.3, 8.3, -4.9, 1.6]
    - [0.0]
    init_time_value: 0.0
    seeds: [291, 0, 0, 0, 0, 0, 11242, 6785, 0, 42, 85, 0, 53425, 62215, 0]
    state_widths: [4, 4, 16, 1, 4, 16, 4, 4, 1, 4, 4, 1, 4, 4, 1]
    state_history_depths: [500, 2, 2, 2, 2, 2, 2, 2, 200, 2, 2, 200, 2, 2, 200]
    timesteps_history_depth: 500
extra_vars_by_package:
- github.com/umbralcalc/stochadex/pkg/kernels:
  - expKernel: "&kernels.ExponentialIntegrationKernel{}"
- github.com/umbralcalc/stochadex/pkg/phenomena:
  - simulationIteration: "&phenomena.OrnsteinUhlenbeckIteration{}"
  - simulationIteration2: "&phenomena.OrnsteinUhlenbeckIteration{}"
  - simulationIteration3: "&phenomena.OrnsteinUhlenbeckIteration{}"
  - dataRollingMean: "&phenomena.WeightedWindowedMeanIteration{Kernel: expKernel}"
  - dataRollingCov: "&phenomena.WeightedWindowedCovarianceIteration{Kernel: expKernel}"
- github.com/umbralcalc/stochadex/pkg/params:
  - simulationReadingParams: "&params.ParamsReaderIteration{Iteration: simulationIteration}"
  - simulationReadingParams2: "&params.ParamsReaderIteration{Iteration: simulationIteration2}"
  - simulationReadingParams3: "&params.ParamsReaderIteration{Iteration: simulationIteration3}"
- github.com/umbralcalc/stochadex/pkg/inference:
  - likelihoodForGen: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp2: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp3: "&inference.NormalLikelihoodDistribution{}"
  - dataStream: "&inference.DataGenerationIteration{Likelihood: likelihoodForGen}"
  - dataComparisonToSimulation: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp}"
  - dataComparisonToSimulation2: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp2}"
  - dataComparisonToSimulation3: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp3}"
  - paramsPosteriorLogNorm: "&inference.PosteriorLogNormalisationIteration{}"
  - paramsPosteriorMean: "&inference.PosteriorMeanIteration{}"
  - paramsPosteriorCov: "&inference.PosteriorCovarianceIteration{}"
  - likelihoodForParamsGen: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForParamsGen2: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForParamsGen3: "&inference.NormalLikelihoodDistribution{}"
  - paramsGeneratingProcess: "&inference.DataGenerationIteration{Likelihood: likelihoodForParamsGen}"
  - paramsGeneratingProcess2: "&inference.DataGenerationIteration{Likelihood: likelihoodForParamsGen2}"
  - paramsGeneratingProcess3: "&inference.DataGenerationIteration{Likelihood: likelihoodForParamsGen3}"