simulator:
  partitions:
  - iteration: dataStream
    params_from_upstream_partition: {}
  - iteration: dataRollingMean
    params_from_upstream_partition:
      "latest_data_values": 0
  - iteration: dataRollingCov
    params_from_upstream_partition:
      "latest_data_values": 0
      "mean": 1
  - iteration: paramsPosteriorLogNorm
    params_from_upstream_partition: {}
  - iteration: paramsPosteriorMean
    params_from_upstream_partition:
      "posterior_log_normalisation": 3
  - iteration: paramsPosteriorCov
    params_from_upstream_partition:
      "posterior_log_normalisation": 3
      "mean": 4
  - iteration: paramsGeneratingProcess
    params_from_upstream_partition:
      "mean": 4
      "covariance_matrix": 5
  - iteration: simulationReadingParams
    params_from_upstream_partition:
      "param_values": 6
  - iteration: dataComparisonToSimulation
    params_from_upstream_partition:
      "mean": 1
      "covariance_matrix": 2
      "latest_data_values": 7
  - iteration: paramsGeneratingProcess2
    params_from_upstream_partition:
      "mean": 4
      "covariance_matrix": 5
  - iteration: simulationReadingParams2
    params_from_upstream_partition:
      "param_values": 9
  - iteration: dataComparisonToSimulation2
    params_from_upstream_partition:
      "mean": 1
      "covariance_matrix": 2
      "latest_data_values": 10
  - iteration: paramsGeneratingProcess3
    params_from_upstream_partition:
      "mean": 4
      "covariance_matrix": 5
  - iteration: simulationReadingParams3
    params_from_upstream_partition:
      "param_values": 12
  - iteration: dataComparisonToSimulation3
    params_from_upstream_partition:
      "mean": 1
      "covariance_matrix": 2
      "latest_data_values": 13
  output_condition: "&simulator.EveryStepOutputCondition{}"
  output_function: "&simulator.StdoutOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 5000}"
  timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
extra_vars_by_package:
- github.com/umbralcalc/stochadex/pkg/kernels:
  - expKernel: "&kernels.ExponentialIntegrationKernel{}"
- github.com/umbralcalc/stochadex/pkg/phenomena:
  - simulationIteration: "&phenomena.OrnsteinUhlenbeckIteration{}"
  - simulationIteration2: "&phenomena.OrnsteinUhlenbeckIteration{}"
  - simulationIteration3: "&phenomena.OrnsteinUhlenbeckIteration{}"
  - dataRollingMean: "&phenomena.WeightedWindowedMeanIteration{Kernel: expKernel}"
  - dataRollingCov: "&phenomena.WeightedWindowedCovarianceIteration{Kernel: expKernel}"
- github.com/umbralcalc/stochadex/pkg/params:
  - simulationReadingParams: "&params.ParamsReaderIteration{Iteration: simulationIteration}"
  - simulationReadingParams2: "&params.ParamsReaderIteration{Iteration: simulationIteration2}"
  - simulationReadingParams3: "&params.ParamsReaderIteration{Iteration: simulationIteration3}"
- github.com/umbralcalc/stochadex/pkg/inference:
  - likelihoodForGen: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp2: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp3: "&inference.NormalLikelihoodDistribution{}"
  - dataStream: "&inference.DataGenerationIteration{Likelihood: likelihoodForGen}"
  - dataComparisonToSimulation: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp}"
  - dataComparisonToSimulation2: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp2}"
  - dataComparisonToSimulation3: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp3}"
  - paramsPosteriorLogNorm: "&inference.PosteriorLogNormalisationIteration{}"
  - paramsPosteriorMean: "&inference.PosteriorMeanIteration{}"
  - paramsPosteriorCov: "&inference.PosteriorCovarianceIteration{}"
  - likelihoodForParamsGen: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForParamsGen2: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForParamsGen3: "&inference.NormalLikelihoodDistribution{}"
  - paramsGeneratingProcess: "&inference.DataGenerationIteration{Likelihood: likelihoodForParamsGen}"
  - paramsGeneratingProcess2: "&inference.DataGenerationIteration{Likelihood: likelihoodForParamsGen2}"
  - paramsGeneratingProcess3: "&inference.DataGenerationIteration{Likelihood: likelihoodForParamsGen3}"