simulation:
  implementations:
    partitions:
    - iteration: dataStream
      params_from_upstream_partition: {}
    - iteration: dataRollingMean
      params_from_upstream_partition:
        "latest_data_values": 0
    - iteration: dataRollingCov
      params_from_upstream_partition:
        "latest_data_values": 0
        "mean": 1
    - iteration: paramsPosteriorResample
      params_from_upstream_partition: {}
    - iteration: ornsteinUhlenbeckSimulation
      params_from_upstream_partition:
        "0/latest_data_values": 1
        "1/latest_data_values": 2
        "2/mus": 3
    - iteration: smoothedLikelihood
      params_from_upstream_partition:
        "latest_data_values": 3
        "latest_function_values": 4
      params_from_indices:
        "latest_function_values": [24]
    output_condition: "&simulator.EveryStepOutputCondition{}"
    output_function: "&simulator.StdoutOutputFunction{}"
    termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 2000}"
    timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
  settings:
    params:
    - mean: [1.8, 5.0, -7.3, 2.2]
      covariance_matrix: [2.5, 0.0, 0.0, 0.0, 0.0, 9.0, 0.0, 0.0, 0.0, 0.0, 4.4, 0.0, 0.0, 0.0, 0.0, 17.0]
    - exponential_weighting_timescale: [100.0]
      data_values_partition: [0]
    - exponential_weighting_timescale: [100.0]
      data_values_partition: [0]
    - past_discounting_factor: [0.8]
      sample_covariance: [0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5]
      param_partitions: [3]
      loglike_partitions: [4]
      loglike_indices: [24]
    - burn_in_steps: [800]
      0/state_memory_partition: [1]
      1/state_memory_partition: [2]
    - past_discounting_factor: [0.8]
      covariance_matrix: [0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5]
      data_values_partition: [3]
      function_values_partition: [4]
      function_values_indices: [24]
    init_state_values:
    - [1.3, 8.3, -4.9, 1.6]
    - [1.1, 4.0, -8.3, 2.0]
    - [4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0]
    - [0.9, 3.5, -4.7, 1.0]
    - [1.1, 4.0, -8.3, 2.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 1.3, 8.3, -4.9, 1.6, 0.0]
    - [0.0]
    init_time_value: 0.0
    seeds: [291, 0, 0, 112322, 6785, 0]
    state_widths: [4, 4, 16, 4, 25, 1]
    state_history_depths: [500, 200, 200, 200, 200, 200]
    timesteps_history_depth: 500
embedded_simulations:
- ornsteinUhlenbeckSimulation:
    implementations:
      partitions:
      - iteration: "&general.MemoryIteration{}"
        params_from_upstream_partition: {}
      - iteration: "&general.MemoryIteration{}"
        params_from_upstream_partition: {}
      - iteration: simulationIteration
        params_from_upstream_partition: {}
      - iteration: dataComparisonToSimulation
        params_from_upstream_partition:
          "mean": 0
          "covariance_matrix": 1
          "latest_data_values": 2
      output_condition: "&simulator.NilOutputCondition{}"
      output_function: "&simulator.NilOutputFunction{}"
      termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 200}"
      timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
    settings:
      params:
      - {}
      - {}
      - mus: [1.0, 4.0, -6.0, 1.0]
        sigmas: [1.5, 3.0, 2.2, 4.1]
        thetas: [1.0, 1.0, 1.0, 1.0]
      - cumulative: [1]
        burn_in_steps: [50]
      init_state_values:
      - [1.1, 4.0, -8.3, 2.0]
      - [4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0]
      - [1.3, 8.3, -4.9, 1.6]
      - [0.0]
      init_time_value: 0.0
      seeds: [0, 0, 6785, 0]
      state_widths: [4, 16, 4, 1]
      state_history_depths: [2, 2, 2, 2]
      timesteps_history_depth: 2
extra_vars_by_package:
- github.com/umbralcalc/stochadex/pkg/kernels:
  - expKernel: "&kernels.ExponentialIntegrationKernel{}"
  - gaussKernel: "&kernels.GaussianIntegrationKernel{}"
- github.com/umbralcalc/stochadex/pkg/continuous:
  - simulationIteration: "&continuous.OrnsteinUhlenbeckIteration{}"
  - dataRollingMean: "&continuous.WeightedWindowedMeanIteration{Kernel: expKernel}"
  - dataRollingCov: "&continuous.WeightedWindowedCovarianceIteration{Kernel: expKernel}"
  - smoothedLikelihood: "&continuous.WeightedWindowedFunctionIteration{Kernel: gaussKernel}"
- github.com/umbralcalc/stochadex/pkg/inference:
  - likelihoodForGen: "&inference.NormalLikelihoodDistribution{}"
  - likelihoodForComp: "&inference.NormalLikelihoodDistribution{}"
  - dataStream: "&inference.DataGenerationIteration{Likelihood: likelihoodForGen}"
  - dataComparisonToSimulation: "&inference.DataComparisonIteration{Likelihood: likelihoodForComp}"
  - paramsPosteriorResample: "&inference.PosteriorImportanceResampleIteration{}"