other_params:
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    drift_coefficients_partition: [0]
    diffusion_coefficients_partition: [1]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    drift_coefficients_partition: [3]
    diffusion_coefficients_partition: [4]
init_state_values:
- [0.45, 1.4, 0.01, -0.13, 0.7]
- [2.0, 1.0, 3.0, 1.1, 7.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.67, -0.01, 0.1]
- [1.0, 2.0, 1.1]
- [0.0, 0.0, 0.0]
init_time_value: 1.0
seeds: [0, 0, 4673, 0, 0, 2783]
state_widths: [5, 5, 5, 3, 3, 3]
state_history_depths: [2, 2, 2, 2, 2, 2]
timesteps_history_depth: 2