other_params:
- float_params:
    extras: []
  int_params: {}
- float_params:
    background_rates: [1.4, 1.2, 0.2, 1.1, 5.0]
    exponential_decays: [0.5, 1.0, 0.2, 1.3, 1.1]
  int_params: {}
init_state_values:
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
seeds: [253, 1112]
state_widths: [5, 5]
state_history_depths: [50, 50]
timesteps_history_depth: 50