other_params:
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: [12]
    downstream_partitions: [5]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: [2]
    downstream_partitions: [8, 11]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: [5]
    downstream_partitions: [11]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: [5, 8]
    downstream_partitions: [12]
- float_params: {}
  int_params:
    partition_indices: [11]
    partition_state_values: [5]
init_state_values:
- [1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [5, 5, 5, 5, 5, -1]
- [1.0, 1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [0, 0, 0, 0, 0, -1, -1]
- [1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [0, 0, 0, 0, 0, -1]
- [1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [0, 0, 0, 0, 0, -1]
- [-1]
seeds: [0, 0, 123563, 0, 0, 352, 0, 0, 11231, 0, 0, 7641, 0]
state_widths: [1, 5, 6, 2, 5, 7, 1, 5, 6, 1, 5, 6, 1]
state_history_depths: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
timesteps_history_depth: 2