other_params:
- float_params:
    player_attacking_run_param: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    player_defensive_run_param: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    player_lateral_run_sigma: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    background_event_rates: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    transition_probs_from_0: []
    transition_probs_from_1: []
    transition_probs_from_2: []
    transition_probs_from_3: []
    transition_probs_from_4: []
    transition_probs_from_5: []
    transition_probs_from_6: []
    transition_probs_from_7: []
    transition_probs_from_8: []
    transition_probs_from_9: []
    transition_probs_from_10: []
    transition_probs_from_11: []
    transition_probs_from_12: []
  int_params:
    transitions_from_0: [8, 5, 2, 4]
    transitions_from_1: [8, 5, 6]
    transitions_from_2: [12]
    transitions_from_3: [12]
    transitions_from_4: [12]
    transitions_from_5: [7, 4, 9, 10, 11, 6, 3]
    transitions_from_6: [7, 4, 9, 10, 11]
    transitions_from_7: [8]
    transitions_from_8: [5, 6]
    transitions_from_9: [5, 6, 10, 11]
    transitions_from_10: [5, 6]
    transitions_from_11: [5, 6]
    transitions_from_12: [5]
init_state_values:
- [12, 0, ]
seeds: [563]
state_widths: [5]
state_history_depths: [2]
timesteps_history_depth: 2