other_params:
- float_params:
    front_row_scrum_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    front_row_lineout_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    front_row_ruck_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    front_row_maul_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    second_row_scrum_possessions: [1.0, 1.0, 1.0, 1.0]
    second_row_lineout_possessions: [1.0, 1.0, 1.0, 1.0]
    second_row_ruck_possessions: [1.0, 1.0, 1.0, 1.0]
    second_row_maul_possessions: [1.0, 1.0, 1.0, 1.0]
    back_row_lineout_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    back_row_ruck_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    back_row_maul_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    centres_ruck_possessions: [1.0, 1.0, 1.0, 1.0]
    player_run_possessions: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    player_attacking_run_scales: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    player_defensive_run_scales: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    player_lateral_run_scales: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    player_fatigue_rates: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
    player_start_times: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
    halves_kick_scales: [1.0, 1.0, 1.0, 1.0]
    back_three_kick_scales: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    halves_kick_accuracies: [1.0, 1.0, 1.0, 1.0]
    back_three_kick_accuracies: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    background_event_rates: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    max_possession_change_rates: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
    transition_probs_from_0: [0.25, 0.25, 0.25, 0.25]
    transition_probs_from_1: [0.333, 0.333, 0.333]
    transition_probs_from_2: [1.0]
    transition_probs_from_3: [1.0]
    transition_probs_from_4: [1.0]
    transition_probs_from_5: [0.142, 0.142, 0.142, 0.142, 0.142, 0.142, 0.142]
    transition_probs_from_6: [0.2, 0.2, 0.2, 0.2, 0.2]
    transition_probs_from_7: [1.0]
    transition_probs_from_8: [0.5, 0.5]
    transition_probs_from_9: [0.25, 0.25, 0.25, 0.25]
    transition_probs_from_10: [0.5, 0.5]
    transition_probs_from_11: [0.5, 0.5]
    transition_probs_from_12: [1.0]
  int_params:
    transitions_from_0: [8, 5, 2, 4]
    transitions_from_1: [8, 5, 6]
    transitions_from_2: [12]
    transitions_from_3: [12]
    transitions_from_4: [12]
    transitions_from_5: [7, 4, 9, 10, 11, 6, 3]
    transitions_from_6: [7, 4, 9, 10, 11]
    transitions_from_7: [8]
    transitions_from_8: [5, 6]
    transitions_from_9: [5, 6, 10, 11]
    transitions_from_10: [5, 6]
    transitions_from_11: [5, 6]
    transitions_from_12: [5]
init_state_values:
- [12, 0, 50.0, 35.0]
seeds: [563]
state_widths: [5]
state_history_depths: [2]
timesteps_history_depth: 2