params:
- neighbour_weightings: [1.0, 1.0, 1.0, 1.0]
  neighbour_partitions: [1, 2, 3, 4]
- variances: [1.0, 1.0, 1.0]
- variances: [1.0, 1.0, 1.0]
- variances: [1.0, 1.0, 1.0]
- variances: [1.0, 1.0, 1.0]
init_state_values:
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
seeds: [325, 1111, 4252, 24, 12]
state_widths: [3, 3, 3, 3, 3]
state_history_depths: [2, 2, 2, 2, 2]
timesteps_history_depth: 2