other_params:
- float_params: 
    variances: [1.0, 1.0, 1.0]
  int_params: {}
- float_params: 
    variances: [1.0, 3.0]
  int_params: {}
- float_params: 
    exponential_weighting_timescale: [1.1]
  int_params:
    data_values_partition: [0]
    function_values_partition: [1]
    function_values_indices: [0, 1]
init_state_values:
- [0.0, 0.0, 0.0]
- [0.0, 0.0]
- [0.0, 0.0]
seeds: [24, 5, 0]
state_widths: [3, 2, 2]
state_history_depths: [30, 30, 2]
timesteps_history_depth: 30