iterations:
- name: embedded_test_partition_1
  params: {}
  init_state_values: [0.45, 1.4, 0.01, -0.13, 0.7]
  seed: 0
  state_width: 5
  state_history_depth: 2
- name: embedded_test_partition_2
  params: {}
  init_state_values: [0.67, -0.01, 0.1]
  seed: 0
  state_width: 3
  state_history_depth: 2
init_time_value: 0.0
timesteps_history_depth: 2