params:
- param_values: [123456]
  user_input_keystroke_action_k: [54321]
  wait_milliseconds: [1]
init_state_values:
- [0.0]
init_time_value: 0.0
seeds: [0]
state_widths: [1]
state_history_depths: [1]
timesteps_history_depth: 1