iterations:
- name: partition_0
  params: {}
  init_state_values: [7.0, 4.5, 1.9]
  seed: 24
  state_width: 3
  state_history_depth: 30
- name: partition_1
  params:
    param_values: [2.0, 3.0]
  init_state_values: [2.0, 5.2]
  seed: 5
  state_width: 2
  state_history_depth: 30
- name: partition_2
  params:
    exponential_weighting_timescale: [1.1]
    data_values_partition: [0]
    other_values_partition: [1]
    other_values_indices: [0, 1]
  params_from_upstream:
    latest_data_values:
      upstream: 0
    latest_other_values:
      upstream: 1
  init_state_values: [0.0, 0.0]
  seed: 0
  state_width: 2
  state_history_depth: 30
- name: partition_3
  params:
    exponential_weighting_timescale: [1.1]
    data_values_partition: [1]
  params_from_upstream:
    latest_data_values:
      upstream: 1
  init_state_values: [0.0, 0.0]
  seed: 0
  state_width: 2
  state_history_depth: 2
init_time_value: 0.0
timesteps_history_depth: 30