params:
- {}
- values_to_count: [0.0, 1.0, 2.0]
  partition_indices: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  state_value_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
- values_to_count: [0.0, 1.0, 2.0]
  state_values: [1.0, 0.0, 2.0, 2.0, 1.0, 1.0, 1.0]
init_state_values:
- [0.0, 1.0, 2.0, 2.0, 2.0, 0.0, 1.0, 0.0, 1.0, 2.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [0, 0, 0]
state_widths: [10, 3, 3]
state_history_depths: [1, 1, 1]
timesteps_history_depth: 1