iterations:
- name: partition_0
  params: {}
  init_state_values: [0.0, 1.0, 2.0, 2.0, 2.0, 0.0, 1.0, 0.0, 1.0, 2.0]
  seed: 0
  state_width: 10
  state_history_depth: 1
- name: partition_1
  params: {}
  init_state_values: [5.0, 2.0, 48.0, 11.0, 621.0, 1.0, 1.0, 2.0, 8.0, 245.0]
  seed: 0
  state_width: 10
  state_history_depth: 1
- name: partition_2
  params:
    accepted_value_group_tupindex_0: [0.0, 1.0, 2.0]
    grouping_partitions_tupindex_0: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    grouping_value_indices_tupindex_0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    state_partitions: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    state_value_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    float_precision: [2]
  params_from_upstream:
    latest_grouping_partition_0:
      upstream: 0
    latest_states_partition_1:
      upstream: 1
  init_state_values: [0.0, 0.0, 0.0]
  seed: 0
  state_width: 3
  state_history_depth: 1
- name: partition_3
  params:
    default_values: [5.0, 5.0, 5.0]
    accepted_value_group_tupindex_0: [0.0, 1.0, 2.0]
    grouping_partitions_tupindex_0: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    grouping_value_indices_tupindex_0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    state_partitions: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    state_value_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    float_precision: [2]
  params_from_upstream:
    latest_grouping_partition_0:
      upstream: 0
    latest_states_partition_1:
      upstream: 1
  init_state_values: [0.0, 0.0, 0.0]
  seed: 0
  state_width: 3
  state_history_depth: 1
init_time_value: 0.0
timesteps_history_depth: 1