iterations:
- params:
    rates: [0.5, 1.0, 0.8, 1.0, 1.1]
    gamma_alphas: [1.0, 2.5, 3.0, 1.8, 1.0]
    gamma_betas: [2.0, 1.0, 4.1, 2.0, 1.2]
  init_state_values: [0.0, 0.0, 0.0, 0.0, 0.0]
  seed: 563
  state_width: 5
  state_history_depth: 2
- params:
    rates: [1.5, 0.2, 0.6]
    gamma_alphas: [2.3, 5.1, 2.0]
    gamma_betas: [2.0, 1.5, 1.1]
  init_state_values: [0.0, 0.0, 0.0]
  seed: 8312
  state_width: 3
  state_history_depth: 2
init_time_value: 0.0
timesteps_history_depth: 2