iterations:
- params: {}
  init_state_values: [0.45, 1.4, 0.01, -0.13, 0.7]
  seed: 0
  state_width: 5
  state_history_depth: 2
- params: {}
  init_state_values: [2.0, 1.0, 3.0, 1.1, 7.0]
  seed: 0
  state_width: 5
  state_history_depth: 2
- params: {}
  params_from_upstream:
    drift_coefficients:
      upstream: 0
    diffusion_coefficients:
      upstream: 1
  init_state_values: [0.0, 0.0, 0.0, 0.0, 0.0]
  seed: 4673
  state_width: 5
  state_history_depth: 2
- params: {}
  init_state_values: [0.67, -0.01, 0.1]
  seed: 0
  state_width: 3
  state_history_depth: 2
- params: {}
  init_state_values: [1.0, 2.0, 1.1]
  seed: 0
  state_width: 3
  state_history_depth: 2
- params: {}
  params_from_upstream:
    drift_coefficients:
      upstream: 3
    diffusion_coefficients:
      upstream: 4
  init_state_values: [0.0, 0.0, 0.0]
  seed: 2783
  state_width: 3
  state_history_depth: 2
init_time_value: 1.0
timesteps_history_depth: 2