iterations:
- name: partition_0
  params: {}
  init_state_values: [0.45, 1.4, 0.01, -0.13, 0.7]
  seed: 0
  state_width: 5
  state_history_depth: 2
- name: partition_1
  params: {}
  init_state_values: [2.0, 1.0, 3.0, 1.1, 7.0]
  seed: 0
  state_width: 5
  state_history_depth: 2
- name: partition_2
  params:
    jump_rates: [0.5, 1.0, 0.8, 1.0, 1.1]
    gamma_alphas: [1.0, 2.5, 3.0, 1.8, 1.0]
    gamma_betas: [2.0, 1.0, 4.1, 2.0, 1.2]
  params_from_upstream:
    drift_coefficients:
      upstream: 0
    diffusion_coefficients:
      upstream: 1
  init_state_values: [0.0, 0.0, 0.0, 0.0, 0.0]
  seed: 4673
  state_width: 5
  state_history_depth: 2
- name: partition_3
  params: {}
  init_state_values: [0.67, -0.01, 0.1]
  seed: 0
  state_width: 3
  state_history_depth: 2
- name: partition_4
  params: {}
  init_state_values: [1.0, 2.0, 1.1]
  seed: 0
  state_width: 3
  state_history_depth: 2
- name: partition_5
  params:
    jump_rates: [1.5, 0.2, 0.6]
    gamma_alphas: [2.3, 5.1, 2.0]
    gamma_betas: [2.0, 1.5, 1.1]
  params_from_upstream:
    drift_coefficients:
      upstream: 3
    diffusion_coefficients:
      upstream: 4
  init_state_values: [0.0, 0.0, 0.0]
  seed: 2783
  state_width: 3
  state_history_depth: 2
init_time_value: 1.0
timesteps_history_depth: 2