iterations:
- name: partition_0
  params:
    variances: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  init_state_values: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  seed: 713
  state_width: 10
  state_history_depth: 2
- name: partition_1
  params:
    variances: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  init_state_values: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  seed: 673
  state_width: 10
  state_history_depth: 2
init_time_value: 1.0
timesteps_history_depth: 2