iterations:
- params:
    mus: [2.3, 0.1, 3.1, 0.3, 0.5]
    sigmas: [2.1, 5.0, 1.0, 1.1, 0.2]
    thetas: [0.2, 1.0, 1.1, 3.4, 1.4]
  init_state_values: [0.45, 1.4, 0.01, -0.13, 0.7]
  seed: 4673
  state_width: 5
  state_history_depth: 2
- params:
    mus: [0.8, 4.1, 5.0]
    sigmas: [1.1, 3.7, 2.3]
    thetas: [0.3, 1.6, 2.0]
  init_state_values: [0.67, -0.01, 0.1]
  seed: 2783
  state_width: 3
  state_history_depth: 2
init_time_value: 1.0
timesteps_history_depth: 2