params:
- mus: [2.3, 0.1, 3.1, 0.3, 0.5]
  sigmas: [2.1, 5.0, 1.0, 1.1, 0.2]
  thetas: [0.2, 1.0, 1.1, 3.4, 1.4]
- mus: [0.8, 4.1, 5.0]
  sigmas: [1.1, 3.7, 2.3]
  thetas: [0.3, 1.6, 2.0]
init_state_values:
- [0.45, 1.4, 0.01, -0.13, 0.7]
- [0.67, -0.01, 0.1]
init_time_value: 1.0
seeds: [4673, 2783]
state_widths: [5, 3]
state_history_depths: [2, 2]
timesteps_history_depth: 2