params:
- variances: [1.0, 1.0, 1.0]
- exponential_weighting_timescale: [1.1]
  data_values_partition: [0]
- exponential_weighting_timescale: [1.1]
  data_values_partition: [0]
init_state_values:
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
seeds: [4252, 0, 0]
state_widths: [3, 3, 9]
state_history_depths: [30, 2, 2]
timesteps_history_depth: 30